#Knowledge Check - 4

**Answer the following questions, download the .ipynb file and submit the file.**
* **Name** : KANDIKATTU VENKATA SAI ROHITH
* **Session** : 6:10 - 9:00
* **CRN** : 72541

## OOPS

1 - Write a Python program to create a **Vehicle class** with **max_speed** and **mileage** instance attributes.

In [1]:
#Write code here!
class Vehicle:
    def __init__(self, max_speed, mileage):
        self.max_speed = max_speed
        self.mileage = mileage

    def display_info(self):
        print(f"Max Speed: {self.max_speed} mph")
        print(f"Mileage: {self.mileage} miles per gallon")

my_car = Vehicle(120, 25)

my_car.display_info()


Max Speed: 120 mph
Mileage: 25 miles per gallon


2 - Create a **Vehicle class** without any variables and methods

In [2]:
#Write code here!
class Vehicle:
    pass

my_car = Vehicle()


3 - Create a child **class Bus** that will inherit all of the variables and methods of the Vehicle class

In [3]:
class Vehicle:

    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage

class Bus(Vehicle):
    pass

my_bus = Bus("My Bus", 60, 10)

print(f"Bus Name: {my_bus.name}")
print(f"Max Speed: {my_bus.max_speed} mph")
print(f"Mileage: {my_bus.mileage} miles per gallon")


Bus Name: My Bus
Max Speed: 60 mph
Mileage: 10 miles per gallon


Create a Bus object that will inherit all of the variables and methods of the parent Vehicle class and display it.

**Expected Output:**

`Vehicle Name: School Volvo Speed: 180 Mileage: 12`

In [4]:
#Write code here!
class Vehicle:
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage

class Bus(Vehicle):
    pass

my_bus = Bus("School Volvo", 180, 12)

print(f"Vehicle Name: {my_bus.name}")
print(f"Speed: {my_bus.max_speed}")
print(f"Mileage: {my_bus.mileage}")



Vehicle Name: School Volvo
Speed: 180
Mileage: 12


4 - Create a **Bus object** that will inherit all of the variables and methods of the parent Vehicle class and display it.

In [5]:
#Write code here!
class Vehicle:
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage

class Bus(Vehicle):
    def display_info(self):
        print(f"Vehicle Name: {self.name}")
        print(f"Speed: {self.max_speed}")
        print(f"Mileage: {self.mileage}")

my_bus = Bus("School Volvo", 180, 12)

my_bus.display_info()


Vehicle Name: School Volvo
Speed: 180
Mileage: 12


### Inheritance and Polymorphism

5 - Create a **Bus class** that inherits from the Vehicle class. Give the capacity argument of `Bus.seating_capacity()` a default value of 50.

Use the following code for your parent Vehicle class.

In [8]:
class Vehicle:
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage

    def seating_capacity(self, capacity):
        return f"The seating capacity of a {self.name} is {capacity} passengers"
class Bus(Vehicle):
    def seating_capacity(self, capacity=50):
        return super().seating_capacity(capacity)

my_bus = Bus("School Volvo", 180, 12)

capacity = my_bus.seating_capacity()
print(capacity)

The seating capacity of a School Volvo is 50 passengers


**Expected Output:**

```The seating capacity of a bus is 50 passengers```

**HINT** - First, use method overriding.
Next, use default method argument in the seating_capacity() method definition of a bus class.

In [10]:
#Write code here!
class Vehicle:
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage

    def seating_capacity(self, capacity):
        return f"The seating capacity of a {self.name} is {capacity} passengers"

class Bus(Vehicle):
    def seating_capacity(self, capacity=50):
        return super().seating_capacity(capacity)

my_bus = Bus("School Volvo", 180, 12)

capacity_message = my_bus.seating_capacity()

print(capacity_message)


The seating capacity of a School Volvo is 50 passengers


6 - Define a property that must have the same value for every class instance (object)

Define a class **attribute”color”** with a default value white. I.e., Every Vehicle should be white.

Use the following code for this exercise.

In [13]:
class Vehicle:
    color = 'white'

    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage

class Bus(Vehicle):
    pass

class Car(Vehicle):
    pass
school_bus = Bus("School Volvo", 180, 12)
audi_q5 = Car("Audi Q5", 240, 18)
print(f"Color: {school_bus.color}, Vehicle name: {school_bus.name}, Speed: {school_bus.max_speed}, Mileage: {school_bus.mileage}")
print(f"Color: {audi_q5.color}, Vehicle name: {audi_q5.name}, Speed: {audi_q5.max_speed}, Mileage: {audi_q5.mileage}")


Color: white, Vehicle name: School Volvo, Speed: 180, Mileage: 12
Color: white, Vehicle name: Audi Q5, Speed: 240, Mileage: 18


**Expected Output:**

```
Color: White, Vehicle name: School Volvo, Speed: 180, Mileage: 12
Color: White, Vehicle name: Audi Q5, Speed: 240, Mileage: 18
```





**HINT** - Define a color as a class variable in a Vehicle class

In [14]:
#Write code here!
class Vehicle:
    color = "White"

    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage

    def display_info(self):
        return f"{self.color} {self.name} Speed: {self.max_speed} Mileage: {self.mileage}"

class Bus(Vehicle):
    pass

class Car(Vehicle):
    pass

school_bus = Bus("School Volvo", 180, 12)
audi_q5 = Car("Audi Q5", 240, 18)

print(school_bus.display_info())
print(audi_q5.display_info())


White School Volvo Speed: 180 Mileage: 12
White Audi Q5 Speed: 240 Mileage: 18


7 - Create a **Bus child class** that inherits from the Vehicle class. The default fare charge of any vehicle is seating capacity * 100. If Vehicle is Bus instance, we need to add an extra 10% on full fare as a maintenance charge. So total fare for bus instance will become the final amount = total fare + 10% of the total fare.

**Note:** The bus seating capacity is 50. so the final fare amount should be 5500. You need to override the `fare()` method of a Vehicle class in Bus class.

Use the following code for your parent Vehicle class. We need to access the parent class from inside a method of a child class.

In [ ]:
class Vehicle:
    def __init__(self, name, mileage, capacity):
        self.name = name
        self.mileage = mileage
        self.capacity = capacity

    def fare(self):
        return self.capacity * 100

class Bus(Vehicle):
    pass

School_bus = Bus("School Volvo", 12, 50)
print("Total Bus fare is:", School_bus.fare())

Total Bus fare is: 5000


**Expected Output:**

```Total Bus fare is: 5500.0```

In [15]:
#Write code here!
class Vehicle:
    def __init__(self, name, max_speed, mileage, capacity):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage
        self.capacity = capacity

    def fare(self):
        base_fare = self.capacity * 100
        return base_fare

class Bus(Vehicle):
    def __init__(self, name, max_speed, mileage):
        super().__init__(name, max_speed, mileage, capacity=50)

    def fare(self):
        base_fare = super().fare()
        maintenance_charge = base_fare * 0.1
        total_fare = base_fare + maintenance_charge
        return total_fare

school_bus = Bus("School Volvo", 180, 12)

total_fare = school_bus.fare()
print(f"Total Bus fare is: {total_fare}")


Total Bus fare is: 5500.0


8 - Check type of an object
Write a program to determine which class a given Bus object belongs to.

In [ ]:
class Vehicle:
    def __init__(self, name, mileage, capacity):
        self.name = name
        self.mileage = mileage
        self.capacity = capacity

class Bus(Vehicle):
    pass

School_bus = Bus("School Volvo", 12, 50)

**HINT** - Use Python’s built-in function `type()`.

In [17]:
#Write code here!
class Vehicle:
    def __init__(self, name, mileage, capacity):
        self.name = name
        self.mileage = mileage
        self.capacity = capacity

class Bus(Vehicle):
    pass

School_bus = Bus("School Volvo", 12, 50)

obj_type = type(School_bus)

is_bus_instance = isinstance(School_bus, Bus)
is_vehicle_instance = isinstance(School_bus, Vehicle)

print(f"The object belongs to the class: {obj_type}")
print(f"Is it an instance of Bus class? {is_bus_instance}")
print(f"Is it an instance of Vehicle class? {is_vehicle_instance}")


The object belongs to the class: <class '__main__.Bus'>
Is it an instance of Bus class? True
Is it an instance of Vehicle class? True


9 - Determine if School_bus is also an instance of the **Vehicle class**

In [ ]:
class Vehicle:
    def __init__(self, name, mileage, capacity):
        self.name = name
        self.mileage = mileage
        self.capacity = capacity

class Bus(Vehicle):
    pass

School_bus = Bus("School Volvo", 12, 50)

**HINT** - Use `isinstance()` function

In [20]:
#Write code here!
class Vehicle:
    def __init__(self, name, mileage, capacity):
        self.name = name
        self.mileage = mileage
        self.capacity = capacity

class Bus(Vehicle):
    pass

School_bus = Bus("School Volvo", 12, 50)

is_vehicle_instance = isinstance(School_bus, Vehicle)

print(f"Is School_bus an instance of the Vehicle class? {is_vehicle_instance}")


Is School_bus an instance of the Vehicle class? True
